compile:
	pandoc cv2024.md -s -c https://lerina.github.io/css/vpkely.css --toc -o cv2024.html
	pandoc cv2024.md --template=template.tex --pdf-engine=xelatex -o cv2024.pdf
    #fr	
    pandoc cv2024_fr.md -s -c https://lerina.github.io/css/vpkely.css --toc -o cv2024_fr.html
	pandoc cv2024_fr.md --template=template_fr.tex --pdf-engine=xelatex -o cv2024_fr.pdf
